export const scaleFactor = 4;

export const dialogueData = {
  industryPortfolio: 'Desde hace tiempo, he intentado reunir todos los conocimientos de mis diferentes experiencias. El resultado de esto es mi Portafolio de IT Industrial. Dale un vistazo haciendo clic en este enlace <a href="https://industrial-it-portfolio.vercel.app/" target="_blank">Portafolio Industrial</a>.',
  rpaPortfolio: 'He trabajado como desarrollador de DPA y RPA en diferentes empresas. Para demostrar mi conocimiento de las diferentes herramientas de RPA y DPA, he construido este portafolio. Dale un vistazo haciendo clic en este enlace <a href="https://rpa-portfolio.vercel.app/" target="_blank">Portafolio DPA/RPA</a>.',
  fullStackPortfolio: 'He trabajado como desarrollador de software en diferentes empresas. Para demostrar mi conocimiento de las diferentes tecnologías Pro Code / Low Code, he construido este portafolio. Dale un vistazo haciendo clic en este enlace <a href="https://full-stack-port-folio.vercel.app/" target="_blank">Portafolio Full Stack</a>.',
  mlPortfolio: 'He estado estudiando y mejorando mi conocimiento en Machine Learning desde hace tiempo. He terminado algunos certificados en este campo y he experimentado con modelos preconstruidos en mis últimos trabajos. Para demostrar mi conocimiento de las diferentes tecnologías de Machine Learning, he construido este portafolio. Dale un vistazo haciendo clic en este enlace <a href="https://ml-developer-portfolio.vercel.app/" target="_blank">Portafolio Machine Learning</a>.',
  infoPoint: "¡Hola a todos! Mi nombre es Manuel Portero Leiva, soy un bien formado desarrollador de software e ingeniero industrial. Me considero un profesional analítico, eficiente y con gran capacidad de resolución de problemas.<br/><br/><Strong><u>Por favor, recorre mi hogar y revisa los diferentes elementos de mi vida profesional</u></strong>. <ul><li><strong>Ve a la TV (Punto 0) </strong> y revisa mi sitio web personal.</li></br><li><strong>Ve a las computadoras</strong> y revisa mis diferentes portafolios. <br/><br/>Desarrollador de ML <Strong>(Punto 1)</Strong><br/><br/> Desarrollador Full Stack <Strong>(Punto 2)</Strong><br/><br/> Desarrollador RPA <Strong>(Punto 3)</Strong><br/><br/> IT Industrial <Strong>(Punto 4)</Strong> </li></br><li><strong>Verifica el certificado</strong> y mira mi educación.</li></br><li><strong>Ve a la siguiente habitación</strong> y revisa los proyectos de mi carrera <Strong>(Punto 6)</Strong> y mis pasatiempos <Strong>(Puntos 5,7,8,9)</Strong>.</li></ul><br/> Visita cada ítem para conocerme un poco mejor :).",
  education: "Se muestra a continuación mi historial educativo. <br/><br/> <strong>Titulaciones académicas</strong>: <br/><br/><strong>Ceu San Pablo:</strong> Máster en prevención de riesgos laborales <br/><br/> <strong>Universitat Autònoma de Barcelona:</strong> Licenciatura en Ingeniería Química <br/><br/><strong>Institut Obert de Catalunya:</strong> Grado administración de sistemas en red <br/><br/><strong>Glasgow Kelvin College:</strong> Grado de desarrollo Web <br/><br/><strong>Barcelona Activa IT Academy:</strong> Cursos de ML/Big Data",
  sofa: "¿Quieres ver la televisión? Te sugiero que revises el contenido multimedia de mi sitio web. <br/><br/> Haz clic en este enlace y dale un vistazo: <a href='https://profesionalwebsite-mpl.vercel.app/' target='_blank'>Sitio web de Manuel Portero</a>.", 
  printer: "Suelo hacer proyectos con mi impresora 3D y mis dispositivos Arduino (MycroPython) en mi tiempo libre. Estoy planeando crear un portafolio pronto, pero todavía no está listo ^^'.", 
  tv: `¿Quieres ver la televisión? Te sugiero que revises el contenido multimedia de mi sitio web. <br/><br/> Por favor, haz clic en este enlace y dale un vistazo: <a href="https://profesionalwebsite-mpl.vercel.app/" target="_blank">Sitio web de Manuel Portero</a>.`,
  bed: "Actualmente estoy establecido en Barcelona, pero he estado viviendo en Glasgow (Reino Unido) desde 2015-2020, por lo que estoy acostumbrado a trabajar con personas de diferentes culturas.<br/><br/> Para demostrar esto, por favor revisa estas dos cartas de referencia de mi período de residencia en el Reino Unido: <br/><br/> KPC Complex: <a href='https://www.dropbox.com/scl/fi/ylx2onabobrqdbp86w4lh/Manuel_ReferenceKPC.pdf?rlkey=wnbczb7yeimgtcc0p92wpeh2l&dl=0' target='_blank'>Referencia de KPC</a> <br/><br/> Repair Cafe: <a href='https://www.dropbox.com/scl/fi/efm5awtt1h3yplh6zt55a/Manuel_ReferenceRepairCafe.pdf?rlkey=db5fceshuq6wkgqufkirrge17&dl=0' target='_blank'>Referencia de R.Cafe</a>",
  printer2: "Suelo hacer proyectos con mi impresora 3D y mis dispositivos Arduino (MycroPython) en mi tiempo libre. Estoy planeando crear un portafolio pronto, pero todavía no está listo ^^'.", 
  projects: "Por favor, consulta a continuación la lista de proyectos de mis estudios. <br/><br/> <strong>Proyectos de Grado</strong>: <br/><br/><strong>Máster en prevención de riesgos laborales : </strong> <a href='https://www.dropbox.com/scl/fi/br7v49r999mykm5zdb03f/PFM-papeleria-herederos-garcia.pdf?rlkey=u5xh9qk8vvovai68c7qlyx99p&dl=0' target='_blank'>Auditoría de la Libreria H.Garcia</a> <br/><br/> <strong>Licenciatura en Ingeniería Química:</strong> <a href='https://www.dropbox.com/scl/fi/t7ns75jccx7x7wgim8pjn/PFC_Caprojams_part01.pdf?rlkey=vywnhx0nkmyti3a7hwg6rh7xd&dl=0' target='_blank'>Construcción de la fábrica de Caprolactama</a> <br/><br/><strong>Grado administración de sistemas en red:</strong> <a href='https://www.dropbox.com/scl/fi/x7pnr93q9umdfm139r3y9/ASX_M14_TEA4_A_Hotel_Dreams_and_Feel.pdf?rlkey=680fk72e61dlj52ko40l52xu0&dl=0' target='_blank'>Construcción de sistema de red de hotel</a> <br/><br/><strong>Grado desarrollo web:</strong> <a href='https://www.youtube.com/watch?v=C8DJYeXkOcI' target='_blank'>Desarrollo de red social</a>",
  languages: "Suelo aprender y practicar idiomas como hobby. Por favor, consulta a continuación mis habilidades en idiomas. <br/><br/> <strong>Idiomas</strong>: <br/><br/><strong>Castellano:</strong> Nativo<br/><br/> <strong>Inglés:</strong> Nativo<br/><br/><strong>Catalán:</strong> Nativo <br/><br/><strong>Italiano:</strong> Alto<br/><br/><strong>Francés:</strong> Intermedio",
  chair: "Contáctame si te gusta esta presentación del juego. <br/><br/> <strong>Autor</strong>: <br/><br/>Manuel Portero Leiva<br/><br/> <a href='https://profesionalwebsite-mpl.vercel.app/hireme' target='_blank'>Detalles de Contacto</a><br/><br/><strong>Atentamente</strong><br/>Manuel Portero Leiva",
  chair2: "Contáctame si te gusta esta presentación del juego. <br/><br/> <strong>Autor</strong>: <br/><br/>Manuel Portero Leiva<br/><br/> <a href='https://profesionalwebsite-mpl.vercel.app/hireme' target='_blank'>Detalles de Contacto</a><br/><br/><strong>Atentamente</strong><br/>Manuel Portero Leiva",
  exit: "Si deseas cerrar esta presentación del juego. Por favor, cierra la pestaña del navegador."
};
